version: '3'

services:
  nav-website:
    image: km4096/nav-website
    container_name: nav-website
    ports:
      - "3000:3000"
    environment:
      - PORT=3000             # 监听端口
      - ADMIN_USERNAME=admin  # 后台用户名
      - ADMIN_PASSWORD=67890 # 后台密码
    volumes:
      - ./database:/app/database  # 持久化数据库文件
    restart: unless-stopped
